:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>
:queues:
  - [default, <%= ENV.fetch('SIDEKIQ_DEFAULT_QUEUE_WEIGHT', 1) %>]
  - [mailers, <%= ENV.fetch('SIDEKIQ_MAILERS_QUEUE_WEIGHT', 1) %>]
  - [data, <%= ENV.fetch('SIDEKIQ_DATA_QUEUE_WEIGHT', 1) %>]